name: Daily YouTube Vertical Live

on:
  schedule:
    # ලංකාවේ වෙලාවෙන් දවල් 1:30 ට (UTC 08:00)
    - cron: '0 8 * * *'
  workflow_dispatch: 

jobs:
  live-stream:
    runs-on: ubuntu-latest
    steps:
      - name: Install FFmpeg & gdown
        run: |
          sudo apt update
          sudo apt install ffmpeg -y
          pip install gdown --break-system-packages

      - name: Download Video from Google Drive
        run: |
          # අලුත් වීඩියෝ ID එක මෙතැනට ඇතුළත් කර ඇත
          gdown 1xDRUXeBooigi16GgJZLu3CK2wMmxfa6y -O video.mp4

      - name: Start Streaming to YouTube (6 Hours)
        env:
          STREAM_KEY: ${{ secrets.YOUTUBE_STREAM_KEY }}
        run: |
          # -t 21600 මගින් හරියටම පැය 6ක් (60*60*6) ස්ට්‍රීම් කරයි
          # -stream_loop -1 මගින් වීඩියෝව ඉවර වූ සැනින් නැවත මුල සිට පටන් ගනී (Loop)
          ffmpeg -re -stream_loop -1 -i video.mp4 \
            -vf "scale=1080:1920:force_original_aspect_ratio=increase,crop=1080:1920" \
            -c:v libx264 -preset veryfast -tune zerolatency -b:v 3000k -g 60 \
            -c:a aac -b:a 128k -ar 44100 \
            -t 21600 \
            -f flv "rtmp://a.rtmp.youtube.com/live2/$STREAM_KEY"
