name: Daily YouTube Vertical Live

on:
  schedule:
    - cron: '30 14 * * *' 
  workflow_dispatch: 

jobs:
  live-stream:
    runs-on: ubuntu-latest
    steps:
      - name: Install FFmpeg & gdown
        run: |
          sudo apt update
          sudo apt install ffmpeg -y
          pip install gdown

      - name: Download Video from Google Drive
        run: |
          # --id කමාන්ඩ් එක ඉවත් කර කෙලින්ම ID එක ලබා දී ඇත
          gdown 1xw_xpBe0WxU3EXmSG6vC11XqHUb1tUqI -O video.mp4

      - name: Start Streaming to YouTube (1 Hour)
        env:
          STREAM_KEY: ${{ secrets.YOUTUBE_STREAM_KEY }}
        run: |
          ffmpeg -re -stream_loop -1 -i video.mp4 -c:v copy -c:a aac -t 3600 -f flv rtmp://a.rtmp.youtube.com/live2/$STREAM_KEY
